backend:
  name: git-gateway
  repo: ioryn/crna
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://calgaryreggio.org/assets/svgs/logo-light-wide.svg

publish_mode: editorial_workflow
media_folder: "src/assets/images/upload"
public_folder: "/assets/images/upload"

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - label: "Date"
        name: "date"
        widget: "datetime"
        time_format: false # Disables time selection
        format: "YYYY-MM-DD" # Specifies date format without time
        - label: "Time(s)"
        name: "times"
        widget: "string"
        required: false
      - { label: "Tags", name: "tags", widget: "list", default: ["event"] }  # Changed default tag to "event"
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }  # Ensure this default remains "post" for blog categorization
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "jobs"
    label: "Jobs"
    folder: "src/content/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["jobs"] }  # Changed default tag to "jobs"
      - { label: "Body", name: "body", widget: "markdown" }
      

  - name: "resources"
    label: "Resources"
    folder: "src/content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["resources"] }
      - { label: "Body", name: "body", widget: "markdown" }